### ISSUE TITLE
[FE00] 슬슬 파일이 많아지면서 머리가 아파옵니다..

### ISSUE THREAD

**Issue by weg901127** [42js/js-piscine-beta-2021-08#93]
제출 룰에 경로까지 써져있는데요 무서워서 css폴더를 만들 수 없습니다
css폴더 만들게 해주세요 엉엉
![스크린샷 2021-08-19 오전 5 46 45](https://user-images.githubusercontent.com/19397975/129969976-dba9de37-0168-441e-97e4-a1f73b26be29.png)

**Comment by MichelleJin12** [comment]
넵! 오늘내로 파일경로 유연하게 수정하도록 하겠습니다~~ 자유롭게 진행해주세요!

**Comment by MichelleJin12** [comment]
핫 너무 늦었네요 ㅜ
`
|                      |                    |
| --------------------:| ------------------ |
|   제출할 폴더 이름 :     |  ex00              |
|   제출할 파일 이름 :     | index.html, App.js, index.js, 이 외 리액트 프로젝트에 필요한 모든 파일|
|   사용 가능한 외부 모듈 : |                    |
|   참고사항 :           |                    |

제출할 파일 이름은 바뀌거나, 제거되거나, 추가되어도 됩니다.
`
최대한 진행하시는 카시너분들께 지장 안가게 수정해보았습니다!!
